<?php

namespace LSI\MarketBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository {
    public function findAdministreProfil($username){
        $qb = $this->createQueryBuilder('u')
                    ->innerJoin('u.administre', 'a.id')
                    ->addSelect('a');

        $qb
            ->where('u.username = :username')
            ->setParameter('username', $username)
            ->andWhere('u.administre = a.id');

        return $qb->getQuery()->getResult();
    }

    public function findMairieProfil($username){
        $qb = $this->createQueryBuilder('u')
                    ->innerJoin('u.mairie', 'm.id')
                    ->addSelect('m');
        $qb
            ->where('u.username = :username')
            ->setParameter('username', $username)
            ->andWhere('u.username = m.id');

        return $qb->getQuery()->getResult();
    }

    public function findAuteurAnnonce($id){
        $qb = $this->createQueryBuilder('u')
            ->join('u.mairie', 'm')
            ->addSelect('m')
        ;

        $qb
            ->where('u.mairie = m.id')
            ->andWhere('m.id = :id')
            ->setParameter('id', $id)

            //->andWhere('m = u.mairie')
        ;
        return $qb->getQuery()->getResult();
    }

    // Lister les administrateurs
    public function findUserAdmin(){
        $roles = 'a:1:{i:0;s:10:"ROLE_ADMIN";}';
        $qb = $this->createQueryBuilder('u')
            ->where('u.roles = :roles')
            ->setParameter('roles', $roles)
            ;
        return $qb->getQuery()->getResult();
    }

    // Afficher le nom de la mairie

    public function findNameMairie(){
        $req = $this->createQueryBuilder('u');

        $req->innerJoin('u.mairie', 'm')
            ->addSelect('m');

            $req->where('m.id != 0')
                ;

    return $req->getQuery()->getResult();


    }
	// Auteur des annonces

    public function findUserAnnonce($id){
       
        $qb = $this->createQueryBuilder('u')
            ;
        $qb->innerJoin('u.mairie', 'm')
            ->addSelect('m')
            ;
        $qb->where('m.id= :id')
            ->setParameter('id', $id)
            ;
        return $qb->getQuery()->getResult();
    }

     // Requête pour la gestion des habilitations

    public function habilitation($id){
        $req = $this->createQueryBuilder('u');

        $req->innerJoin('u.membre', 'm')
            ->addSelect('m')
            ->innerJoin('m.mairie', 'mai')
            ->addSelect('mai')
        ;

        $req->where('mai.id= :id')
            ->setParameter('id', $id);
        return $req->getQuery()->getResult();
    }

    // Récupère la liste des mairies du même EPCI
    public function findMairieEpci($nomEpci, $idMairie){
        $qb = $this->createQueryBuilder('u')
            //->select('u.nom')
            ->join('u.mairie', 'm')
            ->addSelect('m')
            ->join('u.adresse', 'a')
            ->addSelect('a')
            ->join('a.ville', 'v')
            ->addSelect('v')
            ->join('v.epci', 'e')
            ->addSelect('e')
            ;
        $qb->where('e.nom = :nomEpci')
            ->setParameter('nomEpci', $nomEpci)
            ->andWhere('m.id != :idMairie')
            ->setParameter('idMairie', $idMairie)
            ;
        return $qb->getQuery()->getResult();
    }
}
